### ISSUE TITLE
Add Merge Friendly Principle to General Guide

### ISSUE THREAD

**Issue by sergiotaborda** [zbra-solutions/code-conventions#6]
In several sources and communities the easiness of merging in git and other code repositories  is considered a good thing to have. Less conflict lines help to focus the reviewer on the code that matters and help the tools to merge more code automatically. 

This principle will help clarify breaking line rules when explicit rules are not available.

**Comment by sergiotaborda** [comment]
This principle came up in conversation with @spliner who is a fan , and I second it.

**Comment by spliner** [comment]
Can confirm. Am a fan.
